# Generated by Django 4.1.1 on 2022-09-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('fieldType', models.CharField(choices=[('ST', 'string'), ('NU', 'number'), ('LS', 'list')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ListFieldTypeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('formField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms_app.formfield')),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('fields', models.ManyToManyField(related_name='formTemplates', to='forms_app.formfield')),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringValue', models.CharField(max_length=50)),
                ('numberValue', models.FloatField()),
                ('formField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_app.formfield')),
                ('listValue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_app.listfieldtypevalue')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='forms_app.formtemplate'),
        ),
    ]
