# Generated by Django 4.1.1 on 2022-09-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_formfield_listfieldtypevalue_formtemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='fields',
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_app.formtemplate'),
        ),
    ]
