# Generated by Django 4.1.1 on 2022-09-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0003_remove_formtemplate_fields_formfield_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='form',
            new_name='FormTemplate',
        ),
    ]
