# Generated by Django 4.1.1 on 2022-09-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0004_rename_form_formfield_formtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldvalue',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_app.form'),
        ),
    ]
