# Generated by Django 4.1.1 on 2022-09-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0005_formfieldvalue_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='name',
        ),
    ]
