# Generated by Django 4.1.1 on 2022-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0006_remove_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldvalue',
            name='numberValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldvalue',
            name='stringValue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
