# Generated by Django 4.1.1 on 2022-09-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0007_alter_formfieldvalue_numbervalue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListFieldTypeValue',
            new_name='ListValue',
        ),
    ]
