# Generated by Django 4.1.1 on 2022-09-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0008_rename_listfieldtypevalue_listvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='FormTemplate',
            new_name='formTemplate',
        ),
        migrations.AlterField(
            model_name='formfieldvalue',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms_app.form'),
        ),
    ]
