# Generated by Django 4.1.1 on 2022-09-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0009_rename_formtemplate_formfield_formtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldvalue',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms_app.form'),
        ),
    ]
